name: GitHubBuild

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions: [ '7.2', '7.4', '8.0', '8.1']

    steps:
    - uses: actions/checkout@v1
    - name: setup php
      uses: shivammathur/setup-php@v2
      with:
         php-version: ${{ matrix.php-versions }}
         extensions: sqlite3

    - name: Validate composer.json and composer.lock
      run: php $(which composer) validate

    - name: setup templates_c
      run: mkdir templates_c || true

    - name: touch config.local.php
      run: touch config.local.php && php -v

    - name: Install dependencies
      run: php $(which composer) install --prefer-dist -n

    - name: Build/test
      run: PHP_CS_FIXER_IGNORE_ENV=1 php $(which composer) build

    - name: setup coveralls
      run: mkdir -p build/logs || true

    - name: Coveralls
      run: vendor/bin/php-coveralls -x clover.xml || true
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
